[workspace]
members = ["xdp-drop", "xdp-drop-common", "xdp-drop-ebpf"]

resolver = "2"

default-members = ["xdp-drop", "xdp-drop-common"]


[profile.release.package.xdp-drop-ebpf]
debug = 2
codegen-units = 1
