[workspace]
members = ["xdp-hello", "xdp-hello-common", "xdp-hello-ebpf"]

resolver = "2"

default-members = ["xdp-hello", "xdp-hello-common"]

[workspace.package]
edition = "2024"

[profile.release.package.xdp-hello-ebpf]
debug = 2
codegen-units = 1
