[book]
title = "Building eBPF Programs with Aya"
description = "Documentation for developing eBPF programs with Aya"
authors = ["Aya Contributors"]
language = "en"
src = "src"

[build]
build-dir = "site"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
site-url = "https://aya-rs.dev"
git-repository-url = "https://github.com/aya-rs/book"
edit-url-template = "https://github.com/aya-rs/book/edit/main/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true

# TODO: Re-enable once https://github.com/Michael-F-Bryan/mdbook-linkcheck/issues/96 is fixed.
# [output.linkcheck]
